### ISSUE TITLE
Do not depend on assemblage, please

### ISSUE THREAD

**Issue by samoht** [lpw25/doc-ock#52]
Assemblage is not released, so this will make very difficult to release the project properly. Maybe include the generated Makefile directly?

**Comment by lpw25** [comment]
Yeah that is what the no-assemblage branch is for -- although it is not at all up to date at the moment.

**Comment by dbuenzli** [comment]
Could this be tackled please.

**Comment by lpw25** [comment]
It what way? Updating the no-assemblage branch, or switching to another build system?

I was just going to leave it as is until I get around to trying to release this library properly.

**Comment by dbuenzli** [comment]
> It what way? Updating the no-assemblage branch, or switching to another build system?

Whatever. It would be nice if we can pin the repo without having to maintain a pin to a specific assemblage version.

**Comment by lpw25** [comment]
I think that updating the no-assemblage branch would be sufficient for that. That assumes that opam can pin a specific branch in a repo.

**Comment by dbuenzli** [comment]
Does it really have to be that complicated ? Besides you will need to keep `master` and `no-assemblage` in sync or you will forget to do so and I will be annoying for us.

**Comment by lpw25** [comment]
Yeah I suppose I can just commit the assemblage output in the master branch. I'll still need to keep things in sync but meh.

**Comment by lpw25** [comment]
Should now be fixed

**Comment by dbuenzli** [comment]
Thanks !

**Comment by dbuenzli** [comment]
You forgot to update the `opam` file.

**Comment by lpw25** [comment]
Fixed
