### ISSUE TITLE
Resolution regression in switch to Octavius

### ISSUE THREAD

**Issue by dsheets** [lpw25/doc-ock#54]
3d4136f8f892908a28471656d180fc051223f5aa caused resolution regressions at least in:

- top module comment
- tag fields

Also, comments for containers (modules, module types, class, class types) should resolve relative to the container and not relative to the container's parent.

**Comment by dsheets** [comment]
Any progress on this? I tried to track down the top comment and tag field issues but gave up during the env mutation in `lookup`.

**Comment by lpw25** [comment]
I'll have a look this afternoon. Is is only references to local things that are broken in the top module comments? What precisely do you mean by tag fields?

**Comment by dsheets** [comment]
The free form text in a tag:

`@raise Invalid_argument when {!x} isn't a {!M.t}!`

I don't think tag arguments can generally contain references so I've not tested that.

Here are the comment reference resolution issues as I understand them:

- The top comment is resolved in some global namespace so references to the child elements of the module in which the top comment appears go unresolved. If they are qualified with the module name of the compilation unit, they are resolved. This seems like another case of the general container comment scope issue.
- References to compilation units without additional path (i.e. just {!MyOcamlFile}) do not resolve.

**Comment by lpw25** [comment]
The issue with top-comments and other container comment scope issues should be resolved by https://github.com/lpw25/doc-ock/commit/8bde737217098a034200d8fbcc1db54975743f40.

The issue with tag fields should be resolved by: https://github.com/lpw25/doc-ock/commit/31b843a2fee58ca7f495bf0c98c681bab4e2dc27.

**Comment by dsheets** [comment]
Excellent! Thanks!

**Comment by dsheets** [comment]
Oops, the compilation unit references still seem unresolved but that may be on my end.
